repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.0
    hooks:
      # Run the linter.
#      - id: ruff-check
#        args: [ --fix ]
      # Run the formatter.
#      - id: ruff-format
      # Docstring checker/formatter
      - id: ruff-format
        files: src/.*
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        name: mypy src
        files: src/.*
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - types-pytz
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 src
        files: src/.*
        additional_dependencies:
          - flake8-print==5.0.0
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest tests
        language: system
        pass_filenames: false
        always_run: true
